// <auto-generated — overwritten by CI for tagged builds>
using System.Reflection;

[assembly: AssemblyTitle("Umbra.SDK")]
[assembly: AssemblyDescription("A support library for REFramework mod and plugin development.")]
[assembly: AssemblyCompany("CLJunge")]
[assembly: AssemblyProduct("Umbra.SDK")]
[assembly: AssemblyCopyright("Copyright © 2026 Chris-Lennart Junge — MIT License")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("0.0.0-local")]
